* NAME
colorscript - run various shell color scripts

* SYNOPSIS
colorscript [OPTION] [SCRIPT NAME]

* DESCRIPTION
colorscript is a command-line tool for running shell color scripts, a collection of terminal color scripts that provide ANSI art or colorful terminal outputs. You can run specific scripts by name or index, get a random script, list available scripts, and manage blacklisted scripts.

* OPTIONS
** -h, --help, help
    Display this help message and exit.
** -l, --list, list
    List all installed color scripts with their corresponding name and ANSI art.
** -r, --random, random
    Run a random color script from the available scripts.
** -e, --exec, exec
    Run the specified color script by either SCRIPT NAME or INDEX.
** -a, --all, all
    Run all color scripts and display their names along with their ANSI art.
** -b, --blacklist, blacklist
    Blacklist the specified color script by name or index, moving it to a "blacklisted" folder.
** -u, --unblacklist, unblacklist
    Unblacklist the specified color script, moving it back to the main directory.

* FILES
** /usr/bin/colorscript
    The colorscript executable binary.
** /opt/shell-color-scripts
    The directory containing the installed color scripts.
** /opt/shell-color-scripts/blacklisted
    The directory containing the blacklisted scripts.

* EXAMPLES
** colorscript -r
    Run a random shell color script. This can be added to your shell configuration to get a random color script every time you open a terminal.
** colorscript -l
    List all installed shell color scripts, showing their index and name.
** colorscript -e 2
    Run the color script with index 2.
** colorscript -e red.sh
    Run the color script named "red.sh".
** colorscript -b red.sh
    Blacklist the "red.sh" color script by moving it to the blacklisted directory.
** colorscript -u red.sh
    Unblacklist the "red.sh" color script, moving it back to the main directory.
** colorscript -a
    Run all installed color scripts, displaying their names along with their ANSI art.

* AUTHOR
Amal Lalgi (https://github.com/theamallalgi/colorscripts)

* SEE ALSO
bash(1), zsh(1), fish(1), terminal(1)
